name: CD DO functions

on:
  workflow_dispatch:
  push:
    paths:
      # DO functions
      - "packages/"
      - "project.yml"
      # Gh Pages site
      - "site"
  workflow_run:
    workflows: [Provision of Infra via Terraform]
    types:
      - completed

env:
  workflow_dispatch__or__workflow_run: |
    ${{ github.event_name == 'workflow_dispatch' }}
                      ||
    (
      ${{ github.event_name == 'workflow_run' }}
                      &&
      ${{ github.event.workflow_run.conclusion == 'success' }}
    )

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      functions: ${{ steps.filter.outputs.functions }}
      site: ${{ steps.filter.outputs.site }}

    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'none'
        filters: |
          functions:
            - "packages/**"
            - "project.yml"
          site:
            - "site/**"


  deploy-DO-fn:
    name: Deploy DO Functions
    runs-on: ubuntu-latest

    needs: changes
    if: |
      ${{ needs.changes.outputs.functions == 'true' }}
                        ||
      ${{ env.workflow_dispatch__or__workflow_run }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DO App Platform (Functions) deployment
        uses: digitalocean/app_action@v1.1.4
        with:
          app_name: highlow
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}


  deploy-ghp-site:
    name: Deploy site on GitHub Pages
    runs-on: ubuntu-latest

    needs: [changes, deploy-DO-fn]
    if: |
      ${{ needs.changes.outputs.site == 'true' }}
                        ||
      ${{ env.workflow_dispatch__or__workflow_run }}
    env:
      VITE_FUNCTIONS_URL: ${{ secrets.DIGITALOCEAN_APP_LIVE_URL }}
      VITE_BASE: ${{ github.event.repository.name }}

    steps:
      - name: Checkout site code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'site/.nvmrc'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: site
      - name: Build
        run: cd site && npm run build
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/dist
          force_orphan: true
