name: Provision of Infra via Terraform

on:
  workflow_dispatch:
  push:
   paths:
    - "terraform/"

jobs:
  apply:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Change Directory to terraform
      run: cd terraform
    - name: Setup Terrform CLI
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
    - name: Terraform Apply
      id: apply
      if: steps.plan.outcome == 'success'
      run: terraform apply -auto-approve -input=false
    - name: Generate Summary
      env:
        plan-output: "terraform\n${{ steps.plan.outputs.stdout }}"
      run: >-
        echo '
        ## Terraform Initialization ${{ steps.init.outcome }}\n
        ## Terraform Validation ${{ steps.validate.outcome }}\n
        ## Terraform Plan ${{ steps.plan.outcome }}\n

        <details><summary>Show Plan</summary>

        \`\`\`\n
        ${{ env.plan-output }}
        \`\`\`

        </details>

        *Pushed by: @${{ github.actor }}, Action: ${{ github.event_name }}*
        '>> $GITHUB_STEP_SUMMARY
