name: Provision of Infra via Terraform

on:
  workflow_dispatch:
  push:
   paths:
    - "terraform/"

jobs:
  apply:
   runs-on: ubuntu-latest
   defaults:
    run:
      working-directory: terraform

   env:
    TF_VAR_DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Terrform CLI
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}
    - name: Terraform Init
      id: init
      run: terraform init -input=false
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
    - name: Terraform Apply
      id: apply
      if: steps.plan.outcome == 'success'
      run: terraform apply -no-color -auto-approve -input=false
    - name: Terraform Output
      id: output
      if: steps.apply.outcome == 'success'
      run: |
        terraform output -no-color -json > tf_output.json
    - name: Set Required Outputs in Github Secrets
      id: set-gh-secret
      if: steps.output.outcome == 'success'
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh secret set DIGITALOCEAN_APP_LIVE_URL \
        --body "$(cat tf_output.json | jq '.do_app.value.live_url')"
    - name: Generate Summary
      env:
        plan-output: "terraform\n${{ steps.plan.outputs.stdout }}"
        apply-output: "terraform\n${{ steps.apply.outputs.stdout }}"
      run: |
        echo "
        #### Terraform Initialization `${{ steps.init.outcome }}`
        #### Terraform Validation `${{ steps.validate.outcome }}`
        #### Terraform Plan `${{ steps.plan.outcome }}`
        #### Terraform Apply `${{ steps.apply.outcome }}`
        #### Terraform Output `${{ steps.output.outcome }}`
        #### Set Required GitHub Secrets `${{ steps.set-gh-secret.outcome }}`

        <details><summary>Show Plan</summary>

        ```
        ${{ env.plan-output }}
        ```

        </details>

        <details><summary>Show Apply</summary>

        ```
        ${{ env.apply-output }}
        ```

        </details>

        ```json
        $(cat tf_output.json | jq -M '.')
        ```

        **Pushed by: @${{ github.actor }}, Action: ${{ github.event_name }}**
        ">> $GITHUB_STEP_SUMMARY
